name: SpaRcle Engine CI Debug

on:
  push:
    branches:
    - dev
    - features/*
    
  pull_request:
    branches:
    - master
    - dev

env:
  BUILD_TYPE: Debug
  
jobs:
  Preparing:
    name: Preparing
    runs-on: windows-2022

    steps:
      - name: Fetching repo and installing Vulkan SDK
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: TWoolhouse/setup-vulkan-sdk@v1.1.0
        with:
          # SDK Version to install
          version: 1.3.211.0
        
      - name: Updating submodules
        run: git submodule --quiet update --init --recursive --depth 1 --jobs 4    

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: 1.10.2

  Building:
    name: Building
    runs-on: windows-2022
    needs: Preparing

    steps:
      - name: Building with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{github.workspace}}/build
          configure-options: -G Ninja 
          build-options: -j 4
          build-type: $BUILD_TYPE
      
      - name: Testing
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE
