on:
  workflow_call:
    inputs:
      windowsBuildState:
        required: true
        type: string
      linuxBuildState:
        required: true
        type: string
      commitActor:
        required: true
        type: string
      commitSha:
        required: true
        type: string
      commitBranch:
        required: true
        type: string
      commitMessage:
        required: true
        type: string
    secrets:
      CITOKEN:
        required: true

jobs:
  Manager:
    name: Manager.
    runs-on: windows-latest
    steps:
      - name: Getting issue id.
        shell: python
        id: script
        run: |
          import os 
          from pathlib import Path
          import subprocess
          home = str(Path.home())
          commitMessage = os.getenv('commitMessage')
          print(f"Commit message:\n{commitMessage}\n")
          words = commitMessage.split()
          for word in words:
            if word[:10] == "#SR_CLOSE(" and word[10:][:-1].isnumeric():
              print(f"Issue ID: {word[10:][:-1]}")
              f = open(f"{home}env.sh", "a")
              f.write(f"\"issueId={word[10:][:-1]}\" >> $GITHUB_ENV")
              f.close()
        env:
          commitMessage: ${{ inputs.commitMessage }}
      #outputEnv = os.getenv('GITHUB_ENV')
      #cmd = f"echo \"issueId={int(word[10:][:-1])}\" >> \"{outputEnv}\" "

      - run:
          source ~/env.sh
        shell: bash

      - if: inputs.linuxBuildState != 'failure' && inputs.windowsBuildState != 'failure'
        name: Closing the issue.
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${env.issueId}
          comment: Closed automatically by CI.

      - if: inputs.linuxBuildState == 'failure' || inputs.windowsBuildState == 'failure'
        name: Creating an issue.
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.CITOKEN }}
          title: (Build) Build failed. ${{inputs.commitBranch}}
          body: |
            This issue is created automatically by CI.
            Linux Build State: ${{inputs.linuxBuildState}}
            Windows Build State: ${{inputs.windowsBuildState}}
            Commit: ${{inputs.commitSha}}
            Commit Branch: ${{inputs.commitBranch}}
            Commit Author: ${{inputs.commitActor}}
          assignees: ${{inputs.commitActor}}
          labels: build-failed