name: SpaRcle Engine Main CI

on:
  push:
    paths-ignore:
      - 'Documentation/**'
      - '**.md'
    branches:
      - master
      - dev
      - features/*

  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - '**.md'
    branches:
      - master
      - dev
      - features/*

jobs:
  manage:
    name: Handle arguments and choose platform.
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '#SR_CI_NONE')"
    outputs:
      #gbuildRelease: ${{ steps.sBuildRelease.outputs.gbuildRelease }}
      #gbuildDebug: ${{ steps.sBuildDebug.outputs.gbuildDebug }}
      #gartifactPush: ${{ steps.sArtifact.outputs.gartifactPush }}
      #gbuildWindows: ${{ steps.sBuildWindows.outputs.gbuildWindows }}
      #gbuildLinux: ${{ steps.sBuildLinux.outputs.gbuildLinux }}
      buildRelease: ${{ steps.globals.outputs.gbuildRelease }}
      buildDebug: ${{ steps.globals.outputs.gbuildDebug }}
      artifactPush: ${{ steps.globals.outputs.gartifactPush }}
      buildWindows: ${{ steps.globals.outputs.gbuildWindows }}
      buildLinux: ${{ steps.globals.outputs.gbuildLinux }}

    steps:
      - name: Fetching repository.
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - if: "contains(github.event.head_commit.message, '#SR_CI_RELEASE')"
        name: Handling "#SR_CI_RELEASE" argument.
        shell: bash
        run: |
          echo "buildRelease=true" >> "$GITHUB_ENV"

      - if: "contains(github.event.head_commit.message, '#SR_CI_DEBUG')"
        name: Handling "#SR_CI_DEBUG" argument.
        shell: bash
        run: |
          echo "buildDebug=true" >> "$GITHUB_ENV"

      - if: "contains(github.event.head_commit.message, '#SR_CI_ALL')"
        name: Handling "#SR_CI_ALL" argument.
        shell: bash
        run: |
          echo "buildRelease=true" >> "$GITHUB_ENV"
          echo "buildDebug=true" >> "$GITHUB_ENV"

      - if: "contains(github.event.head_commit.message, '#SR_CI_ARTIFACT')"
        name: Handling "#SR_CI_ARTIFACT" argument.
        id: sArtifact
        shell: bash
        run: |
          echo "gartifactPush=true" >> $GITHUB_OUTPUT

      - if: "contains(github.event.head_commit.message, '#SR_CI_LINUX')"
        name: Handling "#SR_CI_LINUX" argument.
        shell: bash
        run: |
          echo "buildLinux=true" >> "$GITHUB_ENV"

      - if: "contains(github.event.head_commit.message, '#SR_CI_WINDOWS')"
        name: Handling "#SR_CI_WINDOWS" argument.
        shell: bash
        run: |
          echo "buildWindows=true" >> "$GITHUB_ENV"

      - if: env.buildRelease != 'true' && env.buildDebug != 'true'
        name: Setting default build type.
        shell: bash
        run: |
          echo "buildDebug=true" >> "$GITHUB_ENV"

      - if: env.buildWindows != 'true' && env.buildLinux != 'true'
        name: Setting default platform type.
        shell: bash
        run: |
          echo "buildWindows=true" >> "$GITHUB_ENV"
          echo "buildLinux=true" >> "$GITHUB_ENV"

      - if: env.buildLinux == 'true'
        name: Set global buildWindows.
        id: sBuildWindows
        run: |
          echo "gbuildWindows=true" >> $GITHUB_OUTPUT

      - if: env.buildWindows == 'true'
        name: Set global buildLinux.
        id: sBuildLinux
        run: |
          echo "gbuildWindows=true" >> $GITHUB_OUTPUT

      - if: env.buildDebug == 'true'
        name: Set global buildDebug.
        id: sBuildDebug
        run: |
          echo "gbuildDebug=true" >> $GITHUB_OUTPUT

      - if: env.buildRelease == 'true'
        name: Set global buildRelease.
        id: sBuildRelease
        run: |
          echo "gbuildDebug=true" >> $GITHUB_OUTPUT
          
      - name: Set global variables.
        id: globals
        run: |
          echo "gbuildDebug=env.buildDebug >> $GITHUB_OUTPUT
          echo "gbuildRelease=env.buildRelease >> $GITHUB_OUTPUT
          echo "gbuildWindows=env.buildWindows >> $GITHUB_OUTPUT
          echo "gbuildLinux=env.buildLinux >> $GITHUB_OUTPUT

      #echo "::set-output name=gartifactPush::$deployment_key_for_api"
  

  BuildWindows:
    name: Windows.
    needs: manage
    if: needs.manage.outputs.buildWindows == 'true'
    uses: ./.github/workflows/WindowsCI.yml
    with:
      buildRelease: needs.manage.outputs.gbuildRelease
      buildDebug: needs.manage.outputs.gbuildDebug
      artifactPush: needs.manage.outputs.gartifactPush

  BuildLinux:
    name: Linux.
    needs: manage
    if: needs.manage.outputs.buildLinux == 'true'
    uses: ./.github/workflows/LinuxCI.yml
    with:
      buildRelease: needs.manage.outputs.gbuildRelease
      buildDebug: needs.manage.outputs.gbuildDebug
      artifactPush: needs.manage.outputs.gartifactPush
